// <auto-generated />
using DDD_Investigation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDD_Investigation.Migrations
{
    [DbContext(typeof(DDDContext))]
    [Migration("20230418004716_new subclass-2")]
    partial class newsubclass2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("CustomerSeq")
                .IncrementsBy(100);

            modelBuilder.HasSequence("OrderItemSeq");

            modelBuilder.HasSequence("OrderSeq");

            modelBuilder.Entity("DDD_Investigation.Domain.BuyerAggregate.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "CustomerSeq");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DDD_Investigation.Domain.OrderAggregate.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "OrderItemSeq");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DDD_Investigation.Domain.Shared.BaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "OrderSeq");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("DDD_Investigation.Domain.OrderAggregate.InPersonOrder", b =>
                {
                    b.HasBaseType("DDD_Investigation.Domain.Shared.BaseOrder");

                    b.Property<int>("InPersonCode")
                        .HasColumnType("int");

                    b.ToTable("InPersonOrders", (string)null);
                });

            modelBuilder.Entity("DDD_Investigation.Domain.OrderAggregate.VirtualOrder", b =>
                {
                    b.HasBaseType("DDD_Investigation.Domain.Shared.BaseOrder");

                    b.Property<decimal>("PostCost")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("VirtualOrders", (string)null);
                });

            modelBuilder.Entity("DDD_Investigation.Domain.OrderAggregate.OrderItem", b =>
                {
                    b.HasOne("DDD_Investigation.Domain.Shared.BaseOrder", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DDD_Investigation.Domain.OrderAggregate.Price", "Price", b1 =>
                        {
                            b1.Property<int>("OrderItemId")
                                .HasColumnType("int");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("DDD_Investigation.Domain.Shared.BaseOrder", b =>
                {
                    b.HasOne("DDD_Investigation.Domain.BuyerAggregate.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDD_Investigation.Domain.OrderAggregate.InPersonOrder", b =>
                {
                    b.HasOne("DDD_Investigation.Domain.Shared.BaseOrder", null)
                        .WithOne()
                        .HasForeignKey("DDD_Investigation.Domain.OrderAggregate.InPersonOrder", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDD_Investigation.Domain.OrderAggregate.VirtualOrder", b =>
                {
                    b.HasOne("DDD_Investigation.Domain.Shared.BaseOrder", null)
                        .WithOne()
                        .HasForeignKey("DDD_Investigation.Domain.OrderAggregate.VirtualOrder", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDD_Investigation.Domain.Shared.BaseOrder", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
